const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.Spritefont2,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Platform,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.TextBox,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg,
		C3.Plugins.Dictionary,
		C3.Plugins.Camera3D,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Keyboard.Exps.StringFromKeyCode,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Acts.ZMoveToObject,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.Text.Exps.UID,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Cnds.CompareX,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetSize
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{str: 0},
	{id: 0},
	{Text: 0},
	{Keyboard: 0},
	{Text2: 0},
	{TextWrite: 0},
	{Array: 0},
	{Sprite2: 0},
	{SpriteFont: 0},
	{Text3: 0},
	{Text4: 0},
	{Browser: 0},
	{Vocap: 0},
	{keyboard2: 0},
	{Text5: 0},
	{Text6: 0},
	{Text7: 0},
	{star: 0},
	{play: 0},
	{Mouse: 0},
	{mouse1412284_: 0},
	{Variable1: 0},
	{back2935454_: 0},
	{Audio: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{bggame: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Platform: 0},
	{Leter2: 0},
	{Particles: 0},
	{speed2: 0},
	{Sine: 0},
	{ufo: 0},
	{SpriteFont2: 0},
	{SpriteFont3: 0},
	{SpriteFont4: 0},
	{SpriteFont5: 0},
	{SpriteFont6: 0},
	{Life: 0},
	{Timer: 0},
	{Timer2: 0},
	{score: 0},
	{Sprite12: 0},
	{m2: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{TextBox: 0},
	{Text8: 0},
	{c1: 0},
	{e2: 0},
	{Sprite19: 0},
	{Text9: 0},
	{e3: 0},
	{e4: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Text10: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Corse: 0},
	{Game: 0},
	{test: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Solid: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{spike: 0},
	{SpriteFont7: 0},
	{Sprite8: 0},
	{bg: 0},
	{Pin: 0},
	{bird: 0},
	{letter: 0},
	{bubble: 0},
	{lifer: 0},
	{Scorer: 0},
	{Howto: 0},
	{speed: 0},
	{write: 0},
	{pass: 0},
	{letterr: 0},
	{typed: 0},
	{bggameover2: 0},
	{word: 0},
	{Miss: 0},
	{Text11: 0},
	{Text12: 0},
	{m1: 0},
	{Sprite11: 0},
	{Sprite13: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{Dictionary: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{e1: 0},
	{e5: 0},
	{volum: 0},
	{c2: 0},
	{c3: 0},
	{c4: 0},
	{c5: 0},
	{Sprite20: 0},
	{Text13: 0},
	{TextInput: 0},
	{Sprite21: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{ก: 0},
	{Text14: 0},
	{Text15: 0},
	{Text16: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{af: 0},
	{Text18: 0},
	{Text17: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{letter2: 0},
	{"3DCamera": 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{Sprite65: 0},
	{Sprite66: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{Sprite69: 0},
	{Sprite70: 0},
	{Sprite71: 0},
	{Sprite72: 0},
	{Sprite73: 0},
	{Sprite74: 0},
	{Sprite75: 0},
	{Sprite76: 0},
	{Sprite77: 0},
	{Sprite78: 0},
	{Sprite79: 0},
	{Num2: 0},
	{Num1: 0},
	{charSum: 0},
	{miss: 0},
	{correct: 0},
	{Start: 0},
	{Covert: 0},
	{UpLow: 0},
	{Line: 0},
	{WordLine2: 0},
	{WordLine3: 0},
	{WordLine4: 0},
	{times: 0},
	{Word: 0},
	{OldPost: 0},
	{OldPost2: 0},
	{OldPost3: 0},
	{OldPost4: 0},
	{current: 0},
	{position: 0},
	{count: 0},
	{count2: 0},
	{count3: 0},
	{count4: 0},
	{i: 0},
	{RandomNumber: 0},
	{Level: 0},
	{Level2: 0},
	{Lifes: 0},
	{Score: 0},
	{mute: 0},
	{missr: 0},
	{Totalword: 0},
	{total: 0},
	{char_queue: 0},
	{Typing: 0},
	{pick_UID: 0},
	{Level6: 0},
	{Level7: 0},
	{Level8: 0},
	{Level9: 0},
	{Level10: 0},
	{switch: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Text2: class extends self.ITextInstance {},
	TextWrite: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	Vocap: class extends self.IArrayInstance {},
	keyboard2: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	star: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	mouse1412284_: class extends self.ISpriteInstance {},
	back2935454_: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	bggame: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Leter2: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	ufo: class extends self.ISpriteInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	SpriteFont4: class extends self.ISpriteFontInstance {},
	SpriteFont5: class extends self.ISpriteFontInstance {},
	SpriteFont6: class extends self.ISpriteFontInstance {},
	Life: class extends self.ISpriteInstance {},
	Timer: class extends self.ISpriteFontInstance {},
	Timer2: class extends self.ISpriteFontInstance {},
	score: class extends self.ISpriteFontInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	m2: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	TextBox: class extends self.ITextInputInstance {},
	Text8: class extends self.ITextInstance {},
	c1: class extends self.ISpriteInstance {},
	e2: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Text9: class extends self.ITextInstance {},
	e3: class extends self.ISpriteInstance {},
	e4: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Text10: class extends self.ITextInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Corse: class extends self.ISpriteInstance {},
	Game: class extends self.ISpriteInstance {},
	test: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	spike: class extends self.ISpriteInstance {},
	SpriteFont7: class extends self.ISpriteFontInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	bird: class extends self.ISpriteInstance {},
	bubble: class extends self.IWorldInstance {},
	lifer: class extends self.ITiledBackgroundInstance {},
	Scorer: class extends self.ITextInstance {},
	Howto: class extends self.ITextInstance {},
	letterr: class extends self.ITextInstance {},
	typed: class extends self.ITextInstance {},
	bggameover2: class extends self.ISpriteInstance {},
	word: class extends self.ITextInstance {},
	Miss: class extends self.ITextInstance {},
	Text11: class extends self.ITextInstance {},
	Text12: class extends self.ITextInstance {},
	m1: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	e1: class extends self.ISpriteInstance {},
	e5: class extends self.ISpriteInstance {},
	volum: class extends self.ISpriteInstance {},
	c2: class extends self.ISpriteInstance {},
	c3: class extends self.ISpriteInstance {},
	c4: class extends self.ISpriteInstance {},
	c5: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Text13: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	ก: class extends self.ITextInstance {},
	Text14: class extends self.ITextInstance {},
	Text15: class extends self.ITextInstance {},
	Text16: class extends self.ITextInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	af: class extends self.ITextInstance {},
	Text18: class extends self.ITextInstance {},
	Text17: class extends self.ITextInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	letter2: class extends self.ITextInstance {},
	_3DCamera: class extends self.IInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	Sprite79: class extends self.ISpriteInstance {}
}